<?php

use Illuminate\Database\Seeder;

class PackegeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $rawData = [
            [
                'name' => 'Đăng tin cam kết cơ bản.',
                'group_package' => 1,
                'sort_description' => 'Nhà tuyển dụng nhận được 25 apply trong 20 ngày',
                'description' => 'Nhà tuyển dụng nhận được 25 apply trong 20 ngày',
                'price' => 5000000,
                'price_sale' => 3500000,
                'is_show' => 1,
                'image' => 'img/iconPackage/yeu_thich.jpg',
                'count_view' => 0,
                'count_day_view' => 0,
                'count_employment_post' => 0,
                'count_day_employment_post' => 0,
                'created_at' => date("Y/m/d H:i:s"),
                'updated_at' => date("Y/m/d H:i:s")
            ], [
                'name' => 'Đăng tin cam kết tốc độ',
                'group_package' => 1,
                'sort_description' => 'Nhà tuyển dụng nhận được 25 apply trong 10 ngày',
                'description' => 'Nhà tuyển dụng nhận được 25 apply trong 10 ngày',
                'price' => 7000000,
                'price_sale' => 4900000,
                'is_show' => 1,
                'image' => 'img/iconPackage/dong_ho.jpg',
                'count_view' => 0,
                'count_day_view' => 0,
                'count_employment_post' => 0,
                'count_day_employment_post' => 0,
                'created_at' => date("Y/m/d H:i:s"),
                'updated_at' => date("Y/m/d H:i:s")
            ], [
                'name' => 'Đăng tin cam kết Sales thị trường',
                'group_package' => 1,
                'sort_description' => 'Nhà tuyển dụng nhận được 8 apply trong 20 ngày',
                'description' => 'Nhà tuyển dụng nhận được 8 apply trong 20 ngày',
                'price' => 5500000,
                'price_sale' => 3850000,
                'is_show' => 1,
                'image' => 'img/iconPackage/bieu_do_cot.jpg',
                'count_view' => 0,
                'count_day_view' => 0,
                'count_employment_post' => 0,
                'count_day_employment_post' => 0,
                'created_at' => date("Y/m/d H:i:s"),
                'updated_at' => date("Y/m/d H:i:s")
            ],
            ['name' => 'Đăng tin cam kết Sales leader/ Giám sát bán hàng',
                'group_package' => 1,
                'sort_description' => 'Nhà tuyển dụng nhận được 8 apply trong 20 ngày',
                'description' => 'Nhà tuyển dụng nhận được 8 apply trong 20 ngày',
                'price' => 8000000,
                'price_sale' => 5600000,
                'is_show' => 1,
                'image' => 'img/iconPackage/con_mat.jpg',
                'count_view' => 0,
                'count_day_view' => 0,
                'count_employment_post' => 0,
                'count_day_employment_post' => 0,
                'created_at' => date("Y/m/d H:i:s"),
                'updated_at' => date("Y/m/d H:i:s")
            ],
            ['name' => 'Đăng tin ưu tiên',
                'group_package' => 1,
                'sort_description' => 'Xuất hiện 2 tuần trên Trang chủ 8 slot',
                'description' => 'Xuất hiện 2 tuần trên Trang chủ 8 slot',
                'price' => 2500000,
                'price_sale' => 2500000,
                'is_show' => 1,
                'image' => 'img\iconPackage\ngoi_sao.jpg',
                'count_view' => 0,
                'count_day_view' => 0,
                'count_employment_post' => 0,
                'count_day_employment_post' => 0,
                'created_at' => date("Y/m/d H:i:s"),
                'updated_at' => date("Y/m/d H:i:s")
            ],
            ['name' => 'Gói 100 CV',
                'group_package' => 2,
                'sort_description' => 'Mở liên hệ với 100 CV',
                'description' => 'Mở liên hệ với 100 CV',
                'price' => 1200000,
                'price_sale' => 1200000,
                'is_show' => 1,
                'image' => 'img/iconPackage/thu_muc_xanh_la_cay.jpg',
                'count_view' => 100,
                'count_day_view' => 30,
                'count_employment_post' => 0,
                'count_day_employment_post' => 0,
                'created_at' => date("Y/m/d H:i:s"),
                'updated_at' => date("Y/m/d H:i:s")
            ],
            ['name' => 'Gói 200 CV',
                'group_package' => 2,
                'sort_description' => 'Mở liên hệ với 200 CV',
                'description' => 'Mở liên hệ với 200 CV',
                'price' => 2200000,
                'price_sale' => 2200000,
                'is_show' => 1,
                'image' => 'img/iconPackage/thu_muc_vang.jpg',
                'count_view' => 200,
                'count_day_view' => 60,
                'count_employment_post' => 0,
                'count_day_employment_post' => 0,
                'created_at' => date("Y/m/d H:i:s"),
                'updated_at' => date("Y/m/d H:i:s")
            ],
            ['name' => 'Gói 500 CV',
                'group_package' => 2,
                'sort_description' => 'Mở liên hệ với 500 CV',
                'description' => 'Mở liên hệ với 500 CV',
                'price' => 5000000,
                'price_sale' => 5000000,
                'is_show' => 1,
                'image' => 'img/iconPackage/thu_muc_xanh_da_troi.jpg',
                'count_view' => 500,
                'count_day_view' => 60,
                'count_employment_post' => 0,
                'count_day_employment_post' => 0,
                'created_at' => date("Y/m/d H:i:s"),
                'updated_at' => date("Y/m/d H:i:s")
            ],
            ['name' => 'Gói 1000 CV',
                'group_package' => 2,
                'sort_description' => 'Mở liên hệ với 1000 CV',
                'description' => 'Mở liên hệ với 1000 CV',
                'price' => 8500000,
                'price_sale' => 8500000,
                'is_show' => 1,
                'image' => 'img/iconPackage/thu_muc_do.jpg',
                'count_view' => 1000,
                'count_day_view' => 60,
                'count_employment_post' => 0,
                'count_day_employment_post' => 0,
                'created_at' => date("Y/m/d H:i:s"),
                'updated_at' => date("Y/m/d H:i:s")
            ],
            ['name' => 'Đăng tin cam kết tốc độ + gói lọc 100 CV',
                'group_package' => 3,
                'sort_description' => 'Đăng tin cam kết tốc độ + gói lọc 100 CV',
                'description' => 'Đăng tin cam kết tốc độ + gói lọc 100 CV',
                'price' => 8200000,
                'price_sale' => 5740000,
                'is_show' => 1,
                'image' => 'img/iconPackage/qua_xanh.jpg',
                'count_view' => 100,
                'count_day_view' => 10,
                'count_employment_post' => 0,
                'count_day_employment_post' => 0,
                'created_at' => date("Y/m/d H:i:s"),
                'updated_at' => date("Y/m/d H:i:s")
            ],
            ['name' => 'Lọc 200 CV + email marketing',
                'group_package' => 3,
                'sort_description' => 'Lọc 200 CV + email marketing',
                'description' => 'Lọc 200 CV + email marketing',
                'price' => 3500000,
                'price_sale' => 2450000,
                'is_show' => 1,
                'image' => 'img/iconPackage/qua_vang.jpg',
                'count_view' => 200,
                'count_day_view' => 60,
                'count_employment_post' => 0,
                'count_day_employment_post' => 0,
                'created_at' => date("Y/m/d H:i:s"),
                'updated_at' => date("Y/m/d H:i:s")
            ],
            ['name' => 'Ứng viên tham dự phỏng vấn',
                'group_package' => 4,
                'sort_description' => 'Ứng viên tham dự phỏng vấn',
                'description' => '- Cam kết sẽ hoàn lại tiền trong 10 ngày sau khi kết thúc chiến dịch nếu không tìm được đặt hẹn được với ứng viên.<br/> - Thời gian của gói ứng viên tham sự phỏng vấn là 22 ngày nằm trong thời gian chạy gói đăng tin cam kết.',
                'price' => 260000,
                'price_sale' => 200000,
                'is_show' => 1,
                'image' => '',
                'count_view' => 0,
                'count_day_view' => 0,
                'count_employment_post' => 0,
                'count_day_employment_post' => 0,
                'created_at' => date("Y/m/d H:i:s"),
                'updated_at' => date("Y/m/d H:i:s")
            ],
            ['name' => 'Nhân sự tiêu chuẩn',
                'group_package' => 5,
                'sort_description' => 'Nhân sự tiêu chuẩn',
                'description' => '- Tìm được ứng viên đúng với chân dung mà Doanh nghiệp mong muốn <br/> - Tìm được ứng viên trong thời gian ngắn, chỉ 10 - 12 ngày. <br/> - Cam kết số lượng ứng viên tham gia phỏng vấn mỗi lần tại doanh nghiệp.<br/> - Doanh nghiệp chỉ phải trả chi phí khi có nhân sự đi làm.<br/> - Cam kết 1 đổi 1 trong 10 ngày kể từ thời điểm nhân sự đi làm.',
                'price' => 2860000,
                'price_sale' => 2200000,
                'is_show' => 1,
                'image' => '',
                'count_view' => 0,
                'count_day_view' => 0,
                'count_employment_post' => 0,
                'count_day_employment_post' => 0,
                'created_at' => date("Y/m/d H:i:s"),
                'updated_at' => date("Y/m/d H:i:s")
            ],
            ['name' => 'Gói Spro gia tốc (2 ngày)',
                'group_package' => 6,
                'sort_description' => 'Gói Spro gia tốc (2 ngày)',
                'description' => 'Với những gói đào tạo nhân sự Sales tại Samacom, giáo án và chương tình đào tạo sẽ được nghiên cứu để phù hợp với chính Doanh nghiệp của bạn, giải quyết vấn đề của bộ phận Kinh doanh 1 cách gốc rễ',
                'price' => 699000,
                'price_sale' => 699000,
                'is_show' => 1,
                'image' => 'img\gallery\1.jpg',
                'count_view' => 0,
                'count_day_view' => 0,
                'count_employment_post' => 0,
                'count_day_employment_post' => 0,
                'created_at' => date("Y/m/d H:i:s"),
                'updated_at' => date("Y/m/d H:i:s")
            ],
            ['name' => 'Gói SPro Inhouse',
                'group_package' => 6,
                'sort_description' => 'Gói SPro Inhouse',
                'description' => 'Với gói này chúng tôi sẽ nghiên cứu cụ thể, chi tiết vấn đề tại doanh nghiệp của bạn. Tìm ra nguyên nhân và giải pháp phù hợp nhất cho doanh nghiệp.',
                'price' => 699000,
                'price_sale' => 699000,
                'is_show' => 1,
                'image' => 'img\gallery\1.jpg',
                'count_view' => 0,
                'count_day_view' => 0,
                'count_employment_post' => 0,
                'count_day_employment_post' => 0,
                'created_at' => date("Y/m/d H:i:s"),
                'updated_at' => date("Y/m/d H:i:s")
            ],
        ];


        \DB::table('package')->insert($rawData);
    }
}
